import { model, Schema } from 'mongoose';
import { isEmail } from 'validator';

const adminSchema = new Schema({
  email: {
    type: String,
    required: [true, 'Please provide an email.'],
    unique: true,
    lowercase: true,
    validator: [isEmail, 'Please provide a valid email.'],
  },
  password: {
    // passwordwill be generated by the program
    // and sent to email if necessary
    type: String,
    select: false,
  },
});

const Admin = model('Admin', adminSchema);

export default Admin;
